### ISSUE TITLE
An option for generating an authors file from a TFS repository

### ISSUE THREAD

**Issue by JohanLarsson** [Techsola/tfvc-migrator#10]
With names an placeholders for email

**Comment by jnm2** [comment]
## Draft design

(alternative suggestions welcome)

<https://github.com/Techsola/tfvc-migrator#command-line-arguments> describes the format of the authors file:

```
DOMAIN\John = John Doe <john@doe.com>
DOMAIN\Jane = Jane Doe <jane@doe.com>
```

If there is no `--authors` argument, the tool already exists with code 1 and a message saying it is required.

If there is one, but no file exists at that path, or the file is blank, the tool should collect all TFVC users and generate a file at that path, and exit with code 1 and a message explaining that it created a file at {path} and instructing the user to complete the lines after `=` with `name <email>`. This behavior should also be documented in CLI help for the `--authors` argument. The file should look _something_ like this:

```
DOMAIN\jmusser = 
DOMAIN\jdoe = 
```

Another option would be to complete the line with `jmusser <jmusser@TODO>` or something, but we should then detect the TODO part and refuse to run until it is properly filled out if the user simply repeats the command.

If there is an incomplete line, it should not prevent the tool from running unless the tool actually needs that entry. `DOMAIN\unreferenceduser = ` should just be ignored.

**Comment by JohanLarsson** [comment]
Or alternative `DOMAIN\John = John Doe <email>`

**Comment by jnm2** [comment]
@JohanLarsson That's something I didn't think of, the Azure DevOps API might give us the display name `John Doe`. If so, let's do that.

We'd check for `<email>` as indicating that it has not been filled out.
